### ISSUE TITLE
[PE-D][Tester B] Ui inconsistencies

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W17-2/tp#117] opened 2022-10-28 18:32 UTC
Inconsistent pricing decimal places (0dp, 1dp, 2dp) 
![Screenshot 2022-10-28 at 4.29.39 PM.png](https://raw.githubusercontent.com/mqchua/ped/master/files/b306122c-47d5-4f1e-ba42-3698c92b514c.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: mqchua/ped#1

**Comment by EmilyOng** [comment] 2022-11-01 13:49
Duplicate of https://github.com/AY2223S1-CS2103T-W17-2/tp/issues/138

**Closed by EmilyOng** 2022-11-01 13:49 UTC
Labels: bug
