### ISSUE TITLE
[PE-D][Tester C] Allow input of invalid date

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W17-2/tp#114] opened 2022-10-28 18:03 UTC
If date such as 30-02-2022 is entered, the backend will automatically switch it to 28-02-2022. 

![image.png](https://raw.githubusercontent.com/ngshijun/ped/main/files/9449aef1-6a05-428b-bd3a-5e7a11ba1eee.png)

![image.png](https://raw.githubusercontent.com/ngshijun/ped/main/files/ddbe4778-d2ad-422f-813c-609739a81012.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: ngshijun/ped#3

**Comment by JasonYapzx** [comment] 2022-11-01 16:49
Similar to Issue https://github.com/AY2223S1-CS2103T-W17-2/tp/issues/116

**Comment by EmilyOng** [comment] 2022-11-06 05:19
Closing as duplicate of https://github.com/AY2223S1-CS2103T-W17-2/tp/issues/116

**Closed by EmilyOng** 2022-11-06 05:19 UTC
Labels: bug, documentation, duplicate, help wanted, priority.LOW
